#pragma once
#define TEX_PADDLE_ID 1
#define TEX_BALL_ID 2
#define TEX_PLAYER1_WIN_ID 3
#define TEX_PLAYER2_WIN_ID 4
#define TEX_SCOREPADDLE_ID 5
#define PADDLE_SPEED 500
#define BALL_SPEED 375
#define QUADTREE_MAXLEVEL 5
